import gsap from 'gsap';
import ScrollTrigger from 'gsap/ScrollTrigger';
import { splitLines } from '../lib/split-lines.js';

/**
 * INTRO (black band)
 * ──────────────────
 * Three beats, sequenced rather than fired at once:
 *   1. The statement rises line by line out of its own mask.
 *   2. The signature wipes on left-to-right, as if being written.
 *   3. The brand grid pops in on a staggered grid sweep.
 *
 * Line splitting is layout-derived, so it re-runs on resize.
 */
export function initIntro() {
  const copy = document.querySelector('[data-reveal-lines]');
  const signature = document.querySelector('[data-signature-svg]');
  const brands = document.querySelector('[data-brands]');

  // ── 1. Statement, line by line ────────────────────────────────
  if (copy) {
    let tween;

    const build = () => {
      tween?.scrollTrigger?.kill();
      tween?.kill();

      // Split each paragraph separately so the blank line between
      // the two Figma paragraphs survives.
      const lines = [...copy.children].flatMap((block) => splitLines(block));
      if (!lines.length) return;

      gsap.set(lines, { yPercent: 110 });
      // The block is held at opacity 0 by motion.css until its lines
      // exist and are masked — otherwise unsplit text paints for a
      // frame. Opacity is deliberately a different property from the
      // line transforms, so GSAP has nothing to misparse.
      gsap.set(copy, { opacity: 1 });

      tween = gsap.to(lines, {
        yPercent: 0,
        duration: 1,
        ease: 'power4.out',
        stagger: 0.07,
        scrollTrigger: {
          trigger: copy,
          start: 'top 78%',
          once: true,
        },
      });
    };

    // Split points come from real layout, so they are only correct
    // once the webfont is in. Measuring against the fallback face
    // yields groups that re-wrap to two lines when Inter lands.
    if (document.fonts?.status === 'loaded') {
      build();
    } else if (document.fonts?.ready) {
      document.fonts.ready.then(() => {
        build();
        ScrollTrigger.refresh();
      });
    } else {
      build();
    }

    // Re-split against the new measure, then let ScrollTrigger
    // recompute the positions it cached.
    let resizeTimer;
    window.addEventListener('resize', () => {
      clearTimeout(resizeTimer);
      resizeTimer = setTimeout(() => {
        build();
        ScrollTrigger.refresh();
      }, 200);
    });
  }

  // ── 2. Signature handwriting ──────────────────────────────────
  // A real stroke-by-stroke trace, not a reveal. The inline SVG holds
  // open CENTERLINE paths (generated by scripts/centerline.py from the
  // filled master), so dashing each one draws along the pen's own route.
  //
  // Segments run END TO END rather than on a stagger, each with a
  // duration proportional to its own length and `ease: 'none'`. That
  // makes the pen travel at one constant speed across the whole
  // signature — a stagger would give 41 overlapping pops instead.
  if (signature) {
    const strokes = [...signature.querySelectorAll('path')];

    if (strokes.length) {
      const lengths = strokes.map((p) => p.getTotalLength());
      const WRITE_TIME = 2.4; // seconds for the whole signature

      // The paths are stroked with `stroke-linecap: round`, and a round
      // cap is drawn at EVERY dash boundary — not just at the path ends.
      // The obvious `dasharray: L` / `dashoffset: L` puts one boundary
      // at path position 0 and the next at L, so both endpoints of every
      // stroke showed a half-round dot before anything was drawn: the
      // whole signature appeared as a field of dots up front.
      //
      // Fix: make the GAP longer than the dash and park the offset so
      // both boundaries sit clear of the path by a margin wider than a
      // cap can reach (a cap extends half the stroke width).
      const w = parseFloat(getComputedStyle(strokes[0]).strokeWidth) || 1.4;
      const margin = w * 2;

      gsap.set(strokes, {
        strokeDasharray: (i) => `${lengths[i]} ${lengths[i] + margin * 2}`,
        strokeDashoffset: (i) => lengths[i] + margin,
      });

      // Each stroke's offset now travels its own length PLUS the margin,
      // so durations are shared out on travel rather than on length —
      // otherwise the margin is dead time and the pen speeds up and
      // slows down from stroke to stroke.
      const travel = lengths.map((l) => l + margin);
      const totalTravel = travel.reduce((sum, n) => sum + n, 0);
      // Only now is it safe to show the SVG — see motion.css.
      gsap.set(signature, { opacity: 1 });

      const write = gsap.timeline({
        scrollTrigger: {
          trigger: signature,
          start: 'top 85%',
          once: true,
        },
      });

      strokes.forEach((path, i) => {
        write.to(path, {
          strokeDashoffset: 0,
          duration: (travel[i] / totalTravel) * WRITE_TIME,
          ease: 'none',
        });
      });
    }
  }

  // ── 3. Brand grid ─────────────────────────────────────────────
  if (brands) {
    gsap.to(brands.querySelectorAll('.brands__item'), {
      opacity: 1,
      y: 0,
      scale: 1,
      duration: 0.7,
      ease: 'power3.out',
      stagger: { each: 0.06, from: 'start' },
      scrollTrigger: {
        trigger: brands,
        start: 'top 85%',
        once: true,
      },
    });
  }
}
